### ISSUE TITLE
Some .dll strings not encrypted

### ISSUE THREAD

**Issue by AmusementGFX** [Lumm1t/obnoxious-framework#1]
If you open the .dll with Notepad++, you can still see some strings/cheat language, despite XorStr being in the code.

Here is two I found: https://imgur.com/a/vZE195d

I know it does not matter but for consistency reasons, considering everything else is encrypted, this should be encrypted as well.

**Comment by Lumm1t** [comment]
I'm too lazy, I'm sorry!
