### ISSUE TITLE
crash fix :) 

### ISSUE THREAD

**Issue by ori1337** [Lumm1t/obnoxious-framework#7]
//FrameStageNotify.h
void __fastcall FrameStageNotify(ClientFrameStage_t Stage)
{
	if (!CGlobal::IsGameReady)
		return;
	if (!CGlobal::IsConnected)
		return;

	C_BaseEntity*  pLocalEntity;

	if (pLocalEntity == nullptr)
		return;

	static auto ofunc = HookTables::pFrameStageNotify->GetTrampoline();

	if (Stage == FRAME_NET_UPDATE_START && CGlobal::IsGameReady && GP_Skins)
		if (GP_Skins->SkinsEnable)
			GP_Skins->PostDataUpdate();

	if (GP_Esp && GP_Esp->SoundEspEnable && CGlobal::IsGameReady && Stage == FRAME_NET_UPDATE_END)
	{
		CUtlVector<SndInfo_t> sndList;
		sndList.RemoveAll();

		I::Sound()->GetActiveSounds(sndList);

		for (int i = 0; i < sndList.Count(); i++)
		{
			if (!sndList[i].m_pOrigin)
				continue;

			if (sndList[i].m_nChannel != 4)
				continue;

			if (!sndList[i].m_bUpdatePositions)
				continue;

			GP_Esp->PlaySound(*sndList[i].m_pOrigin, sndList[i].m_nSoundSource);
		}
	}

	ofunc(Stage);
}

//on Present.h
	CGlobal::IsGameReady = I::Engine()->IsInGame();
	CGlobal::IsConnected = I::Engine()->IsConnected();

old hook is crashing :C

**Comment by AmusementGFX** [comment]
I haven't noticed any crashes when using the hack, you should make a pull request if this fixes it.

**Comment by AmusementGFX** [comment]
I tried encrypting the offsets and the aimbot does not work anymore; but I believe I got the configuration files encrypted.

Maybe you can help?

**Comment by Lumm1t** [comment]
When cheat crashing?

**Comment by juregedicoes** [comment]
When i press Build solution in Visual Studio 2017, it says: 
Error MSB8036	The Windows SDK version 10.0.17134.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".	obnoxious framework	D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets	46
