### ISSUE TITLE
Error when Building Solution

### ISSUE THREAD

**Issue by juregedicoes** [Lumm1t/obnoxious-framework#8]
It doesn't Build and gives an error
Erro	C1083 (Not Possible to open archive include)Não é possível abrir arquivo incluir: 'd3dx9.h': No such file or directory (Compiling Souce file Cheat\3DMenu\3DMenu.cpp)	obnoxious framework	d:\users\user\downloads\obnoxious-framework-master\cheat\include\winheaders.h	24
and all the other 38 errors like this one above

**Comment by AmusementGFX** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=6812
